# Site settings
name: Nicholas Malizia
description: "Spatial Data Scientist"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  nmalizia
#codepen_username: your_codepen_username_goes_here
#facebook_username: your_facebook_username_goes_here
#vk_username: your_vk_username_goes_here
#twitter_username: your_twitter_username_goes_here
#google_plus_username: your_google_plus_username_goes_here
linked_in_username: nmalizia
#vine_username:  your_vine_username_goes_here
instagram_username:  nmalizia
#flickr_username: your_flickr_username_goes_here
#steam_username: your_steam_username_goes_here
#soundcloud_username:  your_soundcloud_username_goes_here
#stack_of_username: your_stack_overflow_account_id_number_goes_here
#reddit_username: your_reddit_username_goes_here
#medium_username:  your_medium_username_goes_here
#tumblr_username: your_tumblr_username_goes_here
#weibo_username: your_weibo_username_goes_here
blog_url: "blog"
email: nmalizia@gmail.com
resume_url: "resume"


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated 
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars0.githubusercontent.com/u/747781?"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"

# Build settings
markdown: kramdown
permalink: pretty
